# The file is generated by:
#   $args

{ pkgs }:

let
  common = pkgs.callPackage ../../common/lib.nix { }; # returns a function

  version = "$version";
  hash = "$hash";

  # $rust_toolchain_url
  rustVersion = "$rust_version";
  cargoLock = {
    # $cargo_lock_url
    lockFile = ./Cargo.lock;
    outputHashes = {
      $output_hashes
    };
  };
  patches = [
    $patches
  ];
in
  common.makePants {
    inherit version hash rustVersion cargoLock patches;
  }
