name: Test
'on': push
jobs:
  build-2-22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: joshainglis
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build '.#"release_2.22.0"'
      - run: touch pants.toml && nix shell '.#"release_2.22.0"' --command pants --version
